### ISSUE TITLE
Feature Request: Looped Gifs

### ISSUE THREAD

**Issue by theredwillow** [gedisony/plugin.video.reddit_viewer#1]
I'd like to have a configuration option to loop gifs. Right now they play once and then close.

**Comment by gedisony** [comment]
Not possible without a huge rewrite.

**Comment by gedisony** [comment]
UPDATE: v3.0.7 - Added option to repeat playback of gif videos. 
let me know if you find a reddit post that does not repeat the gif video so that I can add it.

**Comment by theredwillow** [comment]
Hey, sorry about the late reply. I literally haven't been able to get to my computer in days. Thank you for the fast reply!

I went from version 2.7.1 (it was available in a repo) to v3.0.7. It looks great! I found the option to repeat playback and the function is working. The only thing is that the subreddits reload everytime that I open them now (even when returning from a post). Did I install it incorrectly? (I just copied the git folder into RoamingData/Kodi/addons)

**Comment by gedisony** [comment]
I did not know somebody bundled reddit_viewer in a repo.

I believe you installed it correctly. 
The reloading problem is on the more recent kodi 17 Krypton builds. 
I didn't have them on kodi 16 and the kodi 17 alphas.

**Comment by theredwillow** [comment]
Oh yeah! Your v2.7.1 is on Team Kodi's repository.xbmc.org and another repo I downloaded... I think it's SuperRepo.

I'm running Krypton on Windows 8 myself. Like I said before, v3.0.7 seems to load pretty slow for me (though I really love it). But v2.7.1 loads relatively quick (at least half the time, if not more).

**Comment by gedisony** [comment]
So much was added since v2.7.1 
The addon checks to see if a link leads to an image album or just a single image before showing the subreddit posts. 
This is what likely caused the slowdown. 

I put up a new version v3.0.8.
Settings->General-> Resolve links only when clicked  (set to enabled)
PROS: will make the listing of reddit posts faster 
CONS: clicking on an image post will 50% give you a playback error.
