### ISSUE TITLE
Add an option to show new/top/hot reddit

### ISSUE THREAD

**Issue by wwark** [gedisony/plugin.video.reddit_viewer#2]
Hello, 
Could you please this option to class post on each reddit.

Regards,
Wark.

**Comment by gedisony** [comment]
You specify this on the subreddit list. 
example:
all/new
site:youtube.com/top

**Comment by gedisony** [comment]
You put this option ( new/rising/controversial/top/ ) on the custom subreddit name:

all/controversial
all/rising

**Comment by wwark** [comment]
thanks !
