### ISSUE TITLE
Problem connecting account

### ISSUE THREAD

**Issue by zsquared24** [gedisony/plugin.video.reddit_viewer#3]
I got a new firestick and installed reddit viewer from the kodi repro I wanted to authorize it to show my saved links  on the firestick I have it working on my computer so I went to the link you gave me which would generate the code.  I am the dude that asked you about creating this feature actually lol.  Anyway I generated the code on my computer went and typed it in on the firestick in the reddit qauth area and tried to generate the connection but I got a message that said invalid_grant.  Am I doing something wrong or can you not grant 2 different kodis access to the account or could it be I need to use the old code that connects my computer kodi to reddit.  I really don't know what else to do I made sure the code it generated was correct.  Your help would be greatly appreciated.

**Comment by zsquared24** [comment]
I clicked generate the code on my computer then when I went to the firestick and entered the code it says invalid_grant I tried this with 3 different codes that it generated and got the same message.  Would it work maybe if I used my old code from when i connected it to the kodi on my computer.

**Comment by gedisony** [comment]
After you entered the code, did you press the "Ok" button (this saves the value and closes the settings screen) then came back to the settings screen and clicked on "[Click here to get refresh token with valid code]" ?

The process is very counter-intuitive. Because I could not figure out a way to have the plugin get that code without it being saved first. 



I'll update this step on the next version.

**Comment by gedisony** [comment]
I don't think the code used in a different machine will be accepted.

**Comment by zsquared24** [comment]
I did click the ok button then went back into Oauth before hitting the refresh token for valid code.  I expected it to work so I couldn't figure out what the problem was.   Do I need to completely leave settings or just hit ok and leave the app settings which is what I did.  I thought maybe you aren't allowed to link more than one kodi to it from one account but I am really just guessing.  I know I typed the code in correctly even though I couldn't paste since I was on the firestick I made sure it was right.  I hadn't tried to code connected to my other version of kodi on the computer because I didn't think it would work either.  Was just grasping at straws. I just went to the reddit link in the instructions generated the code then typed it into the Oauth section on Reddit Viewer.  I hit the OK to save then went back into that and hit the Click to get refresh token.  It does a working icon then says invalid_grant.  I may try again with a new code in a little while I will drop a message if I get it to work just cant figure out why it isn't

**Comment by zsquared24** [comment]
Alright, I tried it again and it worked for some reason.  I don't know what the problem could have been I had a problem installing an addon earlier and cleared the cache maybe that had something to do with it. Either way problem solved and you can use more than one kodi on your reddit account it allows multiple tokens to be used which is great.  Thanks again for this great feature.
