### ISSUE TITLE
listSubReddit() content type should be "episodes" rather than "movies"

### ISSUE THREAD

**Issue by nkestrel** [gedisony/plugin.video.reddit_viewer#4]
Please use the "episodes" content type for listSubReddit() rather than "movies" so that the Wall and InfoWall views in the default Estuary skin show titles on each item like the Youtube and RedditTV addons. The "movies" type assumes the thumbnails are posters and don't need a title which is definitely not the case for reddit content.

![Estuary content type comparison](https://i.imgur.com/blYnR4O.jpg)

**Comment by gedisony** [comment]
Thanks,

I made the change. v351
